dist: xenial

language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - TESTER_PHP_BIN="php-cgi"

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN -c tests/php-unix.ini -s ./tests/

after_failure:
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
